/**
 * Single source for unified Terms & Conditions and Privacy Policy (platform + modules).
 */

/** @param {string} moduleKey */
export function resolveModuleLegalKey(moduleKey) {
  const k = String(moduleKey || '').trim();
  if (k === 'reviews') return 'review-reply-ai';
  return k;
}

export const UNIFIED_MODULE_ORDER = ['review-reply-ai', 'delivery-dispatch'];

export const GENERAL_TERMS_SECTIONS = [
  {
    title: '1. Service description',
    content: (
      <p>
        Tavari provides an AI phone receptionist service that answers calls on behalf of your business, handles
        basic inquiries, takes messages, and forwards call summaries to you via email.
      </p>
    ),
  },
  {
    title: '2. User obligations',
    content: (
      <p>
        You agree to use Tavari in compliance with all applicable laws and regulations. You are responsible for
        maintaining the security of your account credentials.
      </p>
    ),
  },
  {
    title: '3. Payment terms and billing',
    content: (
      <p>
        Subscription fees are billed monthly on the same calendar day as your signup date. All fees are non-refundable
        except as required by law. Overage charges apply when usage exceeds your plan&apos;s included minutes.
      </p>
    ),
  },
  {
    title: '4. Cancellation policy',
    content: (
      <p>
        You may cancel your subscription at any time. Cancellation takes effect at the end of your current billing
        period. No refunds are provided for partial billing periods.
      </p>
    ),
  },
  {
    title: '5. Limitation of liability',
    content: (
      <p>
        Tavari is provided &quot;as is&quot; without warranties of any kind. We are not liable for any indirect,
        incidental, or consequential damages arising from your use of the service.
      </p>
    ),
  },
];

export const MODULE_TERMS = {
  'review-reply-ai': {
    id: 'module-review-reply-ai',
    title: 'Review Reply AI — module terms',
    moduleName: 'Review Reply AI',
    version: '1.0.0',
    sections: [
      {
        title: '1. Service description',
        content: (
          <p>
            Review Reply AI is an AI-powered service that generates Google review replies for your business. By
            activating this module, you gain access to automated review response generation tools.
          </p>
        ),
      },
      {
        title: '2. Usage rights and restrictions',
        content: (
          <p>
            You may use Review Reply AI to generate replies for reviews of your business. Generated content is provided
            for your review and should be verified before posting. You are responsible for all content posted using this
            service.
          </p>
        ),
      },
      {
        title: '3. AI-generated content disclaimer',
        content: (
          <>
            <p>All replies generated by Review Reply AI are suggestions created by artificial intelligence. You are solely responsible for:</p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>Reviewing all generated content before publication</li>
              <li>Ensuring accuracy and appropriateness of replies</li>
              <li>Compliance with platform policies (e.g., Google&apos;s review policies)</li>
              <li>Any legal or professional consequences of published replies</li>
            </ul>
          </>
        ),
      },
      {
        title: '4. Subscription and billing',
        content: (
          <p>
            Review Reply AI operates on a monthly subscription basis. Your subscription includes a usage limit for
            generated replies per billing cycle. Additional usage may result in overage charges or require plan upgrades.
          </p>
        ),
      },
      {
        title: '5. Data and privacy',
        content: (
          <p>
            Review Reply AI processes review content and business information to generate replies. All data is handled
            in accordance with our Privacy Policy. Review content and generated replies may be stored for service
            improvement purposes.
          </p>
        ),
      },
      {
        title: '6. Termination',
        content: (
          <p>
            You may cancel your Review Reply AI subscription at any time through your billing settings. Cancellation will
            take effect at the end of your current billing period. Access to the service will continue until the period
            ends.
          </p>
        ),
      },
      {
        title: '7. Limitation of liability',
        content: (
          <>
            <p>Review Reply AI provides AI-generated suggestions. We are not liable for:</p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>Inappropriate or inaccurate generated content</li>
              <li>Consequences of published replies</li>
              <li>Platform policy violations resulting from generated content</li>
              <li>Business reputation impacts</li>
            </ul>
          </>
        ),
      },
      {
        title: '8. Relationship to platform terms',
        content: (
          <p>
            These terms apply specifically to the Review Reply AI module. By activating this module, you agree to these
            terms in addition to Tavari&apos;s general Terms &amp; Conditions above.
          </p>
        ),
      },
    ],
  },
  'delivery-dispatch': {
    id: 'module-delivery-dispatch',
    title: 'Last-Mile Delivery — module terms',
    moduleName: 'Last-Mile Delivery',
    version: '1.0.0',
    sections: [
      {
        title: '1. Service description',
        content: (
          <p>
            Last-Mile Delivery is a platform that connects your business with third-party delivery providers. We facilitate
            the scheduling and coordination of pickup and delivery requests. <strong>We do not perform deliveries ourselves.</strong>{' '}
            All physical delivery services are provided by independent third-party carriers or couriers.
          </p>
        ),
      },
      {
        title: '2. Third-party delivery service',
        content: (
          <>
            <p>Delivery service is provided exclusively by third-party providers. By using Last-Mile Delivery you acknowledge and agree that:</p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>Tavari (and its affiliates) is not a carrier, courier, or delivery company</li>
              <li>We do not employ drivers or operate delivery vehicles</li>
              <li>We act only as a technology platform to connect you with third-party delivery providers</li>
              <li>
                The third-party provider is solely responsible for performing the pickup and delivery, including safety,
                timeliness, handling of goods, and compliance with applicable laws
              </li>
            </ul>
          </>
        ),
      },
      {
        title: '3. Your responsibilities',
        content: (
          <p>
            You are responsible for: providing accurate pickup and delivery addresses and contact information; ensuring
            that goods are properly packaged and lawful to transport; and complying with all applicable laws. You use the
            platform and any third-party delivery service at your own risk.
          </p>
        ),
      },
      {
        title: '4. No warranty as to third-party services',
        content: (
          <p>
            We do not guarantee the quality, safety, timeliness, or legality of any third-party delivery service. We do
            not endorse or assume any responsibility for the conduct, performance, or omissions of any third-party
            delivery provider. Any dispute regarding a delivery (e.g., loss, damage, delay, injury) is between you and
            the third-party provider.
          </p>
        ),
      },
      {
        title: '5. Limitation of liability — third-party delivery',
        content: (
          <>
            <p>
              To the maximum extent permitted by law, Tavari and its affiliates, officers, directors, employees, and
              agents shall not be liable for any loss, damage, delay, injury, or claim arising from or related to the
              acts, errors, or omissions of any third-party delivery provider, including but not limited to:
            </p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>Loss, damage, or theft of goods in transit</li>
              <li>Delays, missed deliveries, or failure to perform</li>
              <li>Personal injury or property damage caused by the third-party provider or its personnel</li>
              <li>Violations of law or regulation by the third-party provider</li>
              <li>Any conduct or service quality of the third-party provider</li>
            </ul>
            <p className="mt-4">
              <strong>
                Liability for the delivery service rests solely with the third-party provider that performs the delivery.
              </strong>{' '}
              You agree to look solely to that provider for any claims arising from the delivery. You release and hold
              harmless Tavari from any such claims to the fullest extent permitted by law.
            </p>
          </>
        ),
      },
      {
        title: '6. General limitation of liability',
        content: (
          <p>
            Except as required by law, our total liability arising from or related to the Last-Mile Delivery module
            (including the platform, matching, or coordination services) is limited to the fees you paid for this module
            in the twelve (12) months preceding the claim. We are not liable for indirect, incidental, consequential, or
            punitive damages.
          </p>
        ),
      },
      {
        title: '7. Subscription and billing',
        content: (
          <p>
            Last-Mile Delivery operates on a subscription basis. Your subscription may include usage limits or fees for
            delivery requests. Additional terms may apply to the third-party provider&apos;s services. You may cancel your
            subscription at any time through your billing settings.
          </p>
        ),
      },
      {
        title: '8. Relationship to platform terms',
        content: (
          <p>
            These terms apply specifically to the Last-Mile Delivery module. By activating this module, you agree to these
            terms in addition to Tavari&apos;s general Terms &amp; Conditions above. Your use of third-party delivery
            services may also be subject to the provider&apos;s own terms and conditions.
          </p>
        ),
      },
    ],
  },
};

export const GENERAL_PRIVACY_SECTIONS = [
  {
    title: '1. Data collection',
    content: (
      <p>
        We collect business information (name, address, phone number, email), call transcripts, caller information, and
        usage data to provide and improve our service.
      </p>
    ),
  },
  {
    title: '2. Data usage',
    content: (
      <p>
        We use your data to provide the AI phone receptionist service, send call summaries, manage billing, and improve
        our service quality.
      </p>
    ),
  },
  {
    title: '3. Data sharing',
    content: (
      <p>
        We share data with third-party service providers (VAPI for AI and telephony, Stripe for billing, AWS for email
        and storage, Telnyx for SMS) as necessary to provide the service.
      </p>
    ),
  },
  {
    title: '4. Data retention',
    content: (
      <p>
        We retain call transcripts and messages for the duration of your account and for a reasonable period after
        cancellation for legal and business purposes.
      </p>
    ),
  },
  {
    title: '5. Your rights',
    content: (
      <p>
        You have the right to access, update, export, and delete your data. You can request data export or account
        deletion from your dashboard settings.
      </p>
    ),
  },
  {
    title: '6. Contact',
    content: <p>For privacy concerns, contact us at info@tanggo.ca</p>,
  },
];

export const MODULE_PRIVACY = {
  'review-reply-ai': {
    id: 'module-review-reply-ai-privacy',
    title: 'Review Reply AI — module privacy',
    moduleName: 'Review Reply AI',
    version: '1.0.0',
    sections: [
      {
        title: '1. Data collection',
        content: (
          <>
            <p>Review Reply AI collects and processes the following information:</p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>
                <strong>Review content:</strong> The text of reviews you submit for reply generation
              </li>
              <li>
                <strong>Business information:</strong> Your business name, industry, and branding preferences
              </li>
              <li>
                <strong>Generated replies:</strong> AI-generated reply suggestions created for your reviews
              </li>
              <li>
                <strong>Usage data:</strong> Number of replies generated, features used, and usage patterns
              </li>
            </ul>
          </>
        ),
      },
      {
        title: '2. How we use your data',
        content: (
          <>
            <p>Review Reply AI uses your data to:</p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>Generate personalized reply suggestions for your reviews</li>
              <li>Improve AI response quality and relevance</li>
              <li>Provide usage statistics and analytics</li>
              <li>Enhance service features and functionality</li>
            </ul>
          </>
        ),
      },
      {
        title: '3. Data storage',
        content: (
          <>
            <p>Review content and generated replies are stored securely and may be retained for:</p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>Service functionality (accessing reply history)</li>
              <li>Service improvement and AI training (anonymized where possible)</li>
              <li>Legal and compliance requirements</li>
            </ul>
          </>
        ),
      },
      {
        title: '4. Data sharing',
        content: (
          <>
            <p>Review Reply AI does not share your review content or generated replies with third parties except:</p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>AI service providers necessary for reply generation (OpenAI)</li>
              <li>When required by law or legal process</li>
              <li>To protect our rights or prevent harm</li>
            </ul>
          </>
        ),
      },
      {
        title: '5. Your rights',
        content: (
          <>
            <p>You have the right to:</p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>Access your review data and generated replies</li>
              <li>Delete specific reviews or generated content</li>
              <li>Export your data</li>
              <li>Opt out of data usage for AI improvement (may affect service quality)</li>
            </ul>
          </>
        ),
      },
      {
        title: '6. Data security',
        content: (
          <p>
            All review content and generated replies are encrypted in transit and at rest. We implement industry-standard
            security measures to protect your data.
          </p>
        ),
      },
      {
        title: '7. Third-party services',
        content: (
          <p>
            Review Reply AI uses OpenAI&apos;s API for reply generation. Review content is sent to OpenAI for processing
            in accordance with OpenAI&apos;s privacy policy and data processing terms.
          </p>
        ),
      },
      {
        title: '8. Relationship to platform privacy policy',
        content: (
          <p>
            This section applies specifically to the Review Reply AI module. Your use of this module is also governed by
            Tavari&apos;s general Privacy Policy above.
          </p>
        ),
      },
    ],
  },
  'delivery-dispatch': {
    id: 'module-delivery-dispatch-privacy',
    title: 'Last-Mile Delivery — module privacy',
    moduleName: 'Last-Mile Delivery',
    version: '1.0.0',
    sections: [
      {
        title: '1. Data collection',
        content: (
          <>
            <p>Last-Mile Delivery collects and processes the following information:</p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>
                <strong>Pickup and delivery addresses</strong> you provide when requesting a delivery
              </li>
              <li>
                <strong>Contact information</strong> (e.g., phone number, recipient name) for coordination and communication
              </li>
              <li>
                <strong>Package or shipment details</strong> (e.g., description, priority) that you submit
              </li>
              <li>
                <strong>Saved addresses</strong> and location labels you store for convenience
              </li>
              <li>
                <strong>Usage data</strong> such as delivery requests, status, and account activity
              </li>
            </ul>
          </>
        ),
      },
      {
        title: '2. How we use your data',
        content: (
          <>
            <p>We use your data to:</p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>Facilitate and coordinate pickup and delivery requests</li>
              <li>Share necessary information with third-party delivery providers so they can perform the delivery</li>
              <li>Display your delivery history and saved addresses within the platform</li>
              <li>Provide support, improve the service, and comply with legal obligations</li>
            </ul>
          </>
        ),
      },
      {
        title: '3. Sharing with third-party delivery providers',
        content: (
          <>
            <p>
              <strong>Delivery is performed by independent third-party providers.</strong> To fulfill your delivery
              requests, we share with those providers the information necessary to perform the pickup and delivery, such as:
            </p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>Pickup and delivery addresses</li>
              <li>Contact phone numbers and recipient names</li>
              <li>Package descriptions and priority</li>
            </ul>
            <p className="mt-4">
              Those third-party providers have their own privacy practices and may use your information in accordance with
              their policies and applicable law. We do not control their handling of your data once it has been shared for
              the purpose of performing the delivery. We are not responsible for the privacy practices of third-party
              delivery providers.
            </p>
          </>
        ),
      },
      {
        title: '4. Data storage and retention',
        content: (
          <p>
            We store pickup and delivery data, saved addresses, and request history for as long as needed to provide the
            service, support your account, and meet legal and compliance requirements. You may delete saved addresses through
            the platform; historical delivery records may be retained for operational and legal purposes.
          </p>
        ),
      },
      {
        title: '5. Your rights',
        content: (
          <p>
            You have the right to access, correct, or delete the data you provide (e.g., saved addresses). You may also
            request information about how we process your data. Requests can be made through your account settings or by
            contacting us. Note that we must share certain data with third-party delivery providers to complete deliveries;
            we cannot control how they retain or use that data.
          </p>
        ),
      },
      {
        title: '6. Data security',
        content: (
          <p>
            We use reasonable technical and organizational measures to protect your data. Data is encrypted in transit and
            stored securely. Information shared with third-party delivery providers is subject to their own security
            practices.
          </p>
        ),
      },
      {
        title: '7. Third-party providers and liability',
        content: (
          <p>
            Last-Mile Delivery relies on third-party providers to perform actual deliveries. We are not responsible for their
            privacy practices, data handling, or any harm arising from their use of your information. Your use of the
            delivery service is subject to our Terms &amp; Conditions for this module, which allocate responsibility to the
            third-party delivery provider for the delivery service itself.
          </p>
        ),
      },
      {
        title: '8. Relationship to platform privacy policy',
        content: (
          <p>
            This section applies specifically to the Last-Mile Delivery module. Your use of this module is also governed by
            Tavari&apos;s general Privacy Policy above.
          </p>
        ),
      },
    ],
  },
};
